title: Carlos de Obaldía 
description: Welcome to Carlos' personal page
google_analytics: UA-161851372-1
show_downloads: true
theme: jekyll-theme-minimal
logo: logo_plain.png
show_downloads: false

plugins:
  - jekyll-mentions
