title: Carlos de Obaldía
description: Wellcome to the Carlos' personal page
google_analytics: UA-161851372-1
show_downloads: true
theme: jekyll-theme-minimal
logo: logo_plain.png
show_downloads: false

gems:
  - jekyll-mentions
