title: Carlos de Obaldía Pastor
description: Welcome to Carlos' personal page
google_analytics: UA-161851372-1
show_downloads: true
theme: jekyll-theme-minimal
logo: assets/img/logo.png
show_downloads: false

plugins:
  - jekyll-mentions
